# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo_miniture',
        ),
    ]
