# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=64)),
                ('blob', models.ImageField(max_length=255, upload_to=b'BlobStorage')),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='author',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
