# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0003_auto_20161029_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='desctiption',
            field=models.CharField(default=datetime.datetime(2016, 10, 30, 13, 10, 13, 762388, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
