# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_auto_20161130_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height_miniature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='width_miniature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_miniature',
            field=models.ImageField(height_field='height_miniature', null=True, upload_to='', width_field='width_miniature'),
        ),
    ]
