# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-03 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0005_auto_20161130_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_miniture',
            name='big_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galery.Photo'),
        ),
    ]
