# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-29 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161022_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 29, 16, 28, 13, 319476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 29, 16, 28, 13, 318476, tzinfo=utc)),
        ),
    ]
