# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161029_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 13, 9, 49, 323990, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 13, 9, 49, 322990, tzinfo=utc)),
        ),
    ]
