# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161030_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.AddField(
            model_name='event',
            name='begin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 1, 10, 19, 58, 460003, tzinfo=utc)),
        ),
    ]
