# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161101_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 4, 20, 57, 3, 663995, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
